### PR TITLE
fix NoMethodError

### PR DESCRIPTION
**Pull request by paddor**
lib/minitest/minitest_reporter_plugin.rb:49:in `all_reporters': undefined method `reporters' for Minitest::Reporters:Module (NoMethodError)

### CODE REVIEW

**Comment by os97673** [comment]
Could you please describe the situation when the exception is thrown

**Comment by paddor** [comment]
It happens when I run something like `rake test` in various projects, namely https://github.com/mtortonesi/ruby-czmq-ffi and https://github.com/methodmissing/rbczmq. With this change, they don't fail to startup anymore.

**Comment by paddor** [comment]
It happens when I run something like `rake test` in various projects, namely https://github.com/mtortonesi/ruby-czmq-ffi and https://github.com/methodmissing/rbczmq. With this change, they don't fail to startup anymore.

**Comment by os97673** [comment]
Well, I was unable to play with ruby-czmq-ffi, but I see that it can not even run `rake test` with empty gemset, it doesn't specify dependency on minitest and ffi.
As for rbczmq it started w/o problems.  How can I reproduce the problem?

**Comment by moxley** [comment]
@os97673: I got the same error. I was able to resolve it by requiring "minitest/reporters":

```
require "minitest/reporters"
```

**Comment by os97673** [comment]
please provide a test which reproduces the problem.  I'm sure we have the problem I'm not sure the fix is the best one we have.

**Comment by moxley** [comment]
It's not a problem with the gem, it's a problem [between the chair and keyboard](https://en.wiktionary.org/wiki/PEBCAK).

```
gem install minitest-reporters
echo "require 'minitest/autorun'; class MyTest < Minitest::Test; def test_nothing; end; end" > my_test.rb
ruby -I test my_test.rb
```

**Comment by os97673** [comment]
Thank you for the contribution but I've decided to fix this another way.  If minitest reporters are not initialised then the wrapper uses reporters it has got in ctor.  This way we do not affect the behavior for people who has the gem installed but do not use it.

**Pull request closed without merging**
