### PR TITLE
Prepend run hooks in Minitest::Test

### PR DESCRIPTION
**Pull request by cyrilchampier**
This PR use the prepend behavior instead of class_eval patching.

Right now, 
if I want to add behavior to `Minitest::Test#run`,
and I include `minitest-reporters`,
I am forced to prepend to `Minitest::Test#run_with_hooks`.

### CODE REVIEW

**Comment by cyrilchampier** [comment]
Hum did not though about that, only available in ruby > 2, 
and I guess we dont want to raise minimum ruby version for that ?

**Comment by os97673** [comment]
> Hum did not though about that, only available in ruby > 2,
> and I guess we dont want to raise minimum ruby version for that ?

I'd prefer to not change required version for now.

**Comment by cyrilchampier** [comment]
I understand.
Can we keep this pr open until that requirement changes ?

**Comment by os97673** [comment]
> Can we keep this pr open until that requirement changes ?

sure, it you make other changes (remove unsupported rubies from Travis' config and update required ruby in gemspec ;)

**Comment by cyrilchampier** [comment]
Not sure about what you say:
that if I upgrade everything now, we can change required version now ?
or that I should make this branch build green now, to have it green for when you will change required version ?

**Comment by os97673** [comment]
I meant to make it green (by removing "unsupported" version of ruby)

**Comment by cyrilchampier** [comment]
ok, I will do that next week then, thanks.

**Comment by cyrilchampier** [comment]
Hi @os97673 this seems stale, do I close the PR?

**Comment by os97673** [comment]
> Hi @os97673 this seems stale, do I close the PR?

it depends :)  If you are willing to refresh it you are welcome to do this if not then please close it.

**Comment by cyrilchampier** [comment]
well, i changed my laptop and do not have all the necessary setup, i close it then.

**Pull request closed without merging**
