### PR TITLE
Allows SpecReporter to only report failures

### PR DESCRIPTION
**Pull request by chrisnicola**
I found the test output a bit noisy in development and it was more useful to just report failures instead of everything.

### CODE REVIEW

**Comment by chrisnicola** [comment]
I should add, the reason printing the test.class.name is needed is that because we only output the name on failures the `puts suite` line in before_suite isn't called normally. So we have to output this for the failed tests.

**Comment by os97673** [comment]
> I should add, the reason printing the test.class.name is needed is that because we only output the name on failures the puts suite line in before_suite isn't called normally. So we have to output this for the failed tests.

As I said it would be better to not print class name every time test is fails, but the only stopper for the PR now is redundant method overriding.  As soon as it will be removed PR will be merged.

**Comment by chrisnicola** [comment]
What would you print instead when the test fails, just the test line? Why wouldn't you print the text context name? It isn't technically a "class name" it is constructed from the "describes" calls. The test name usually helps identify which test file you're calling.

**Comment by os97673** [comment]
I was thinking about caching suite name and printing it upon the first failure.

**Comment by chrisnicola** [comment]
Instead of for each failure from that suite? Yeah that sounds fine. I'll try to do that.

**Comment by os97673** [comment]
> Instead of for each failure from that suite?

yep, exactly.

> Yeah that sounds fine. I'll try to do that.

Thanks for your time.  Let me known when you will either implement this or decide to not do this (in this round)

**Comment by tmertens** [comment]
@chrisnicola Any update on this?  It would be a potential alternative to https://github.com/kern/minitest-reporters/pull/131 for fast test suites.  I'll circle around and try to wrap up that PR today, it got sidelined by a number of other higher priority projects.

My biggest issue with the solution here is the complete lack of feedback when tests are passing.  You could have a test hang in the middle of a long-running test suite and wouldn't know it until well after the tests would otherwise have finished running, since zero output would otherwise indicate tests are running happily in the background.  I wonder if this wouldn't be worth putting as optional output for the Progress formatter instead.

For example, the progress bar is displayed while tests are passing.  When a failure occurs, add one or two blank lines and then print the test info and failure message. Add another blank line or two and begin printing the progress bar again (or the next failure message if multiple tests fail in succession).

Thoughts?  The lack of feedback for passing tests would definitely prohibit me from using this formatter when running our slow, 3000+ test suite locally.

**Comment by os97673** [comment]
Well, I'd prefer to not mix Spec and Progress formatters' functionality.  Though I agree that lack of feedback for passing tests is a valid concern.  Perhaps we should not filter passed tests out but after the suite completed print information about all failed tests?

**Comment by tmertens** [comment]
> I'd prefer to not mix Spec and Progress formatters' functionality.
It could always be a new formatter, subclassed off of Progress (or just as its own class).

> Perhaps we should not filter passed tests out but after the suite completed print information about all failed tests?

That is what is already implemented in #131, I just need to move that formatter to its own file.

**Comment by os97673** [comment]
>> Perhaps we should not filter passed tests out but after the suite completed print information about all failed tests?

> That is what is already implemented in #131, I just need to move that formatter to its own file.

ok, so I'm closing the PR and awaiting a new PR with a new formatter.

**Pull request closed without merging**
