### PR TITLE
test for loading error added

### PR DESCRIPTION
**Pull request by os97673**
test provided in #267 by @prettycoder

### CODE REVIEW

**Comment by Paxa** [comment]
It solved my problem

**Comment by os97673** [comment]
@kradima since I'm basically re-fix @265 in this PR could you please test it with RubyMine on your tests.
I'll wait couple days before integrating it into master and publishing a new beta.

**Comment by os97673** [comment]
pushed directly to master to avoid redundant merge

**Comment by os97673** [comment]
1.3.2.beta1 has been release, please test

**Comment by kradima** [comment]
@os97673 Thank you for the notification, I asked our QA team to check and got report that everything works fine in RubyMine.

**Pull request closed without merging**
