### PR TITLE
Override Minitest.parallel_fork_stat_reporter if it's available

### PR DESCRIPTION
**Pull request by pnomolos**
- Provides integration with minitest-parallel_fork > 1.0.2

/cc @jeremyevans

### CODE REVIEW

**Comment by os97673** [comment]
Sorry for late response: could you please clarify what is the purpose of the method you want to add?

**Comment by pnomolos** [comment]
@os97673 See https://github.com/jeremyevans/minitest-parallel_fork/commit/a3c55aa3292c4357f8e1d0390c1a8f6613467236#diff-b9aaa6d358fee521899490d21e5475dbR43 - this will allow minitest-reporters to play nicely with minitest-parallel_fork :)

**Comment by os97673** [comment]
Hmm, so you need some StatisticsReporter.  Am I right? If we have more than one such reporters which one we should return from the method.  More information on what you do expect would be helpful.

**Comment by pnomolos** [comment]
`StatisticsReporter` is from minitest core - the default reporter.  Because minitest-parallel_fork checks for an `is_a?` as opposed to checking on method names (or similar) it currently doesn't play nicely with minitest-reporters (fails badly).  All I'm wanting to do here is to have minitest-parallel_fork properly pick up the minitest-reporters `DelegateReporter`

**Comment by os97673** [comment]
I am not sure I understand what you actually want to achieve :(
Could you please describe what problem do you have, how we fail and how the
change will help to fix the problem you have.

The problem on my side that I only see the solution you implemented but do
not understand what it solves and why it solution and the code itself is
meaningless from minitest-reporters point of view :(

On Oct 2, 2017 4:59 PM, "Phil Schalm" <notifications@github.com> wrote:

StatisticsReporter is from minitest core - the default reporter. Because
minitest-parallel_fork checks for an is_a? as opposed to checking on method
names (or similar) it currently doesn't play nicely with minitest-reporters
(fails badly). All I'm wanting to do here is to have minitest-parallel_fork
properly pick up the minitest-reporters DelegateReporter

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/kern/minitest-reporters/pull/238#issuecomment-333699073>,
or mute the thread

**Comment by os97673** [comment]
closing due to lack of response :(

**Pull request closed without merging**
